---
version: 0.2
phases:
  build:
    commands:
      - env
      - ls -l 
      - cat testfolder/testfile.txt
      - echo $CODEBUILD_WEBHOOK_EVENT


  post_build:
    commands:
      - echo 'Bye !'
